language: node_js
node_js:
- '0.10'
before_install: npm install -g mocha
deploy:
  provider: s3
  access_key_id: AKIAJRJFYD64JIVPLKWQ
  secret_access_key:
    secure: bsgvL38WQKSyLrfjqFb8CY+bSPrVd/exM2SFFbhg5PRhjsRs7wvLPDwdI1rrNnyFo17SR7w5ThSa1juv1pS69GO+9lIcp46CZjWg+N4vpFnhZdBVedGaWQTqaHe+vn4M5lDeN54hfbFRNbSg9FC+L5B2NFQMf290YdXgZIxjEME=
  bucket: deploy-weeia
  upload-dir: radek
  on:
    repo: radamus/cilab7
